### ISSUE TITLE
Missing files when compiling

### ISSUE THREAD

**Issue by FHedin** [LLNL/callpath#9]
Hi,

I try to compile the code using backtrace ; 

I got the following missing header error : 

`fatal error: io_utils.h: No such file or directory`

Is there an undocumented  extra library I should install ?

Best ,

FHedin

**Comment by tgamblin** [comment]
Yes, you want https://github.com/LLNL/adept-utils.

I'll leave this issue open as we should really document this.

**Comment by FHedin** [comment]
Thanks,

but I have already compiled and installed adept-utils, and I did use the following cmake command for building callpath: 

`CC=gcc CXX=g++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH="$HOME/bin/adept-utils" ..`

However I still get the not found header issue

**Comment by FHedin** [comment]
Problem solved, it was because of an incomplete build of the dependency adept-utils, resulting in missing header files.
